In [1]:
# !pip list

In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

In [3]:
# 0. 브라우저 가동
browser = webdriver.Chrome()
browser.maximize_window() # 창 최대화

In [4]:
# 1. 페이지 이동
url = 'https://finance.naver.com/sise/sise_market_sum.naver?&page='
browser.get(url)

In [5]:
# 2. 조회 항목 초기화(체크되어 있는 항목 체크 해제)
checkboxes = browser.find_elements(by=By.NAME, value='fieldIds') #'//*[@id="option1"]'
for checkbox in checkboxes:
    if checkbox.is_selected(): # 체크된 상태라면?
        checkbox.click() # 클릭해서 체크해제

# 3. 조회 항목 체크(원하는 항목)
items_to_select = ['영업이익', '자산총계', '매출액']
for checkbox in checkboxes:
    parent = checkbox.find_element(by=By.XPATH, value='..') # 부모 element
    label = parent.find_element(by=By.TAG_NAME, value = 'label')
    
    if label.text in items_to_select:
        checkbox.click()
# 4. 적용하기 버튼 클릭
# <a href="javascript:fieldSubmit()"><img src="https://ssl.pstatic.net/imgstock/images5/btn_apply.gif" alt="적용하기" width="55" height="18"></a>
# btn_apply = browser.find_element(By.XPATH, value = '//*[@id="contentarea_left"]/div[2]/form/div/div/div/a[1]')
btn_apply = browser.find_element(By.XPATH, value = '//a[@href="javascript:fieldSubmit()"]') # //는 전체 html태그에서 찾는다는 뜻, a는 a태그, @속성 = 값
btn_apply.click()

In [6]:
 # 페이지 분석을 위해 lxml 패키지 설치 필요
!pip install lxml

Requirement already satisfied: lxml in c:\users\desktop\anaconda3\envs\crawler\lib\site-packages (4.9.3)

In [29]:
# 5. 데이터 추출
df = pd.read_html(browser.page_source)[1]
df = df.dropna(axis=0, how='all')
df['N'] = df['N'].astype(int)
df = df.set_index('N')

df = df.dropna(axis=1, how='all')
df

,종목명,현재가,전일비,등락률,액면가,매출액,자산총계,영업이익
N,,,,,,,,
1,삼성전자,69800.0,800.0,-1.13%,100.0,3022314.0,4484245.0,433766.0
2,LG에너지솔루션,560000.0,18000.0,+3.32%,500.0,255986.0,382994.0,12137.0
3,SK하이닉스,123400.0,4600.0,-3.59%,5000.0,446216.0,1038715.0,68094.0
4,삼성바이오로직스,766000.0,18000.0,-2.30%,2500.0,30013.0,165821.0,9836.0
5,POSCO홀딩스,642000.0,23000.0,+3.72%,5000.0,847502.0,984068.0,48501.0
6,삼성전자우,57400.0,1200.0,-2.05%,100.0,NaN,NaN,NaN
7,LG화학,648000.0,2000.0,-0.31%,5000.0,518649.0,679738.0,29957.0
8,삼성SDI,665000.0,2000.0,+0.30%,5000.0,201241.0,302575.0,18080.0
9,현대차,196000.0,800.0,-0.41%,5000.0,1425275.0,2557425.0,98198.0
10,포스코퓨처엠,527000.0,17000.0,+3.33%,500.0,33019.0,46375.0,1659.0
11,NAVER,227000.0,16000.0,+7.58%,100.0,82201.0,338990.0,13047.0
12,기아,82700.0,1500.0,-1.78%,5000.0,865590.0,737110.0,72331.0
13,카카오,51300.0,700.0,+1.38%,100.0,71068.0,229635.0,5803.0
14,현대모비스,233000.0,500.0,+0.22%,5000.0,519063.0,554067.0,20265.0
15,셀트리온,146600.0,2800.0,+1.95%,1000.0,22840.0,58917.0,6472.0
16,KB금융,51000.0,100.0,-0.20%,5000.0,888959.0,7011708.0,56389.0
17,SK이노베이션,216000.0,26500.0,+13.98%,5000.0,780569.0,672189.0,39173.0
18,삼성물산,103300.0,400.0,+0.39%,100.0,431617.0,589815.0,25285.0
19,신한지주,35050.0,150.0,+0.43%,5000.0,354133.0,6758843.0,58881.0
20,LG전자,108400.0,2200.0,-1.99%,5000.0,834673.0,551561.0,35510.0
21,포스코인터내셔널,90100.0,10100.0,+12.63%,5000.0,379896.0,125163.0,9025.0
22,삼성생명,69800.0,700.0,+1.01%,500.0,403310.0,3161659.0,13866.0
23,LG,83500.0,200.0,-0.24%,5000.0,71860.0,296337.0,19414.0
24,HD현대중공업,139700.0,4000.0,+2.95%,5000.0,90455.0,162894.0,-2892.0
25,카카오뱅크,26000.0,700.0,+2.77%,5000.0,16058.0,395161.0,3532.0
26,한국전력,19210.0,170.0,-0.88%,5000.0,712579.0,2348050.0,-326552.0
27,하나금융지주,39300.0,400.0,-1.01%,5000.0,708438.0,5688732.0,46903.0
28,삼성화재,244000.0,1500.0,+0.62%,500.0,257844.0,882243.0,16061.0
29,KT&G,82600.0,800.0,-0.96%,5000.0,58514.0,123017.0,12676.0
30,두산에너빌리티,17490.0,10.0,+0.06%,5000.0,154211.0,230498.0,11061.0
31,SK,152800.0,2100.0,+1.39%,200.0,1345516.0,1945059.0,80047.0
32,하이브,262500.0,4000.0,+1.55%,500.0,17762.0,48704.0,2369.0
33,삼성전기,145400.0,1000.0,+0.69%,5000.0,94246.0,109972.0,11828.0
34,메리츠금융지주,49200.0,1000.0,+2.07%,500.0,703656.0,927572.0,22009.0
35,한화오션,46750.0,1550.0,+3.43%,5000.0,48602.0,122357.0,-16136.0
36,SK텔레콤,46100.0,300.0,+0.66%,100.0,173050.0,313083.0,16121.0
37,삼성에스디에스,128300.0,5600.0,+4.56%,500.0,172347.0,119524.0,9161.0
38,고려아연,494000.0,4000.0,+0.82%,5000.0,112194.0,120979.0,9192.0
39,금양,159100.0,25000.0,+18.64%,500.0,2131.0,2828.0,132.0
40,대한항공,24600.0,50.0,+0.20%,5000.0,140961.0,289977.0,28306.0
41,HD한국조선해양,123300.0,400.0,-0.32%,5000.0,173020.0,298835.0,-3556.0
42,HMM,17490.0,120.0,-0.68%,5000.0,185828.0,259735.0,99516.0
43,우리금융지주,11650.0,170.0,+1.48%,5000.0,423727.0,4804744.0,44305.0
44,S-Oil,74900.0,2000.0,+2.74%,2500.0,424460.0,196131.0,34052.0
45,크래프톤,171800.0,3000.0,+1.78%,100.0,18540.0,60303.0,7516.0
46,기업은행,10390.0,10.0,+0.10%,5000.0,275361.0,4319797.0,37748.0
47,삼성중공업,9030.0,140.0,+1.57%,1000.0,59447.0,144917.0,-8544.0
48,KT,29500.0,200.0,-0.67%,5000.0,256500.0,409807.0,16901.0
49,SK아이이테크놀로지,107300.0,5100.0,+4.99%,1000.0,5858.0,34973.0,-523.0
50,삼성엔지니어링,37000.0,1250.0,+3.50%,5000.0,100543.0,78487.0,7029.0

In [31]:
import os

# 6. 파일 저장
f_name = 'sise.csv'
if os.path.exists(f_name): # 파일이 있다면? 헤더 제외
    df.to_csv(f_name, encoding='utf-8-sig', index=False, mode='a', header=False) # append
else:
    df.to_csv(f_name, encoding='utf-8-sig', index=False)

print(f'{idx} 페이지 완료')

In [ ]:
# 5. 데이터 추출(반복)
for idx in range(1, 40):
    # 사전 작업 : 페이지 이동
    browser.get('')

    df = pd.read_html(browser.page_source)[1]
    df = df.dropna(axis=0, how='all')
    df['N'] = df['N'].astype(int)
    df = df.set_index('N')

    df = df.dropna(axis=1, how='all')
    df

browser.quit()

In [7]:
import re

text = "92151 pts/0    00:00:00 chrome\
  92155 pts/0    00:00:00 cat\
  92156 pts/0    00:00:00 cat\
  92162 pts/0    00:00:00 chrome\
  92163 pts/0    00:00:00 chrome\
  92178 pts/0    00:00:00 chrome\
  92179 pts/0    00:00:00 chrome\
  92223 pts/0    00:00:00 chrome\
  92255 pts/0    00:00:00 chrome\
  92259 pts/0    00:00:00 cat\
  92260 pts/0    00:00:00 cat\
  92266 pts/0    00:00:00 chrome\
  92267 pts/0    00:00:00 chrome <defunct>\
  94436 pts/0    00:00:00 chrome\
  94537 pts/0    00:00:00 chrome\
  94739 pts/0    00:00:00 ps"

a = list(map(int, re.findall(r'(\d{5})', text)))
for i in a:
    print(i, end=' ')

92151 92155 92156 92162 92163 92178 92179 92223 92255 92259 92260 92266 92267 94436 94537 94739

92151 92155 92156 92162 92163 92178 92179 92223 92255 92259 92260 92266 92267 94436 94537 94739

In [20]:
# 우분투 명령어 실행
NAVER_STATE = 0b0001
if NAVER_STATE & 0b0001:
    print('naver')

GOOGLE_SCHOLAR_STATE = 0b0010
KRX_STATE = 0b0100
KOREA_ECONOMY_STATE = 0b1000

if NAVER_STATE|0 == NAVER_STATE:
    print('naver')

True

In [195]:
import random
os_list = [
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 10.0; Win64; x64",
    "Windows NT 6.1; Win64; x64",
    "Macintosh; Intel Mac OS X 10_15_7",
]
# 브라우저 버전 리스트
chrome_version = "Chrome/115.0.0.0 "
safari_version = "Safari/537.36 "
edge_version = 'Edg/115.0.1901.188 '
# 모바일 여부 리스트
mobile_versions = ["Mobile" if random.random() < 0.5 else "" for _ in range(50)]
os = random.choice(os_list)
if('Macintosh; Intel Mac OS X 10_15_7' == os):
    browser_version = safari_version
else:
    browser_version = random.choice([chrome_version + safari_version, chrome_version + safari_version, chrome_version + safari_version, chrome_version + safari_version, safari_version, chrome_version + safari_version + edge_version])
browser_version = browser_version.strip()
user_agent = "Mozilla/5.0 ({}) AppleWebKit/537.36 (KHTML, like Gecko) {}".format(os, browser_version)
print(user_agent.strip())

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

In [1]:
!pip install pandas_datareader

Collecting pandas_datareader
  Downloading pandas_datareader-0.10.0-py3-none-any.whl (109 kB)
     ---------------------------------------- 0.0/109.5 kB ? eta -:--:--
     -------------------------------------- 109.5/109.5 kB 2.1 MB/s eta 0:00:00
Collecting lxml (from pandas_datareader)
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/7a/2f/61afbbb627e910d83613f198ceea270376f6708f52a95b534db10c67b4eb/lxml-4.9.3-cp38-cp38-win_amd64.whl.metadata
  Using cached lxml-4.9.3-cp38-cp38-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: pandas>=0.23 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas_datareader) (2.0.3)
Collecting requests>=2.19.0 (from pandas_datareader)
  Obtaining dependency information for requests>=2.19.0 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=0.23->pandas_datareader) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=0.23->pandas_datareader) (1.24.4)
Collecting charset-normalizer<4,>=2 (from requests>=2.19.0->pandas_datareader)
  Obtaining dependency information for charset-normalizer<4,>=2 from https://files.pythonhosted.org/packages/6b/b2/9d0c8fe83572a37bd66150399e289d8e96d62eca359ffa67c021b4120887/charset_normalizer-3.2.0-cp38-cp38-win_amd64.whl.metadata
  Using cached charset_normalizer-3.2.0-cp38-cp38-win_amd64.whl.metadata (31 kB)
Collecting idna<4,>=2.5 (from requests>=2.19.0->pandas_datareader)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.19.0->pandas_datareader)
  Obtaining dependency information for urllib3<3,>=1.21.1 from https://files.pythonhosted.org/packages/9b/81/62fd61001fa4b9d0df6e31d47ff49cfa9de4af03adecf339c7bc30656b37/urllib3-2.0.4-py3-none-any.whl.metadata
  Using cached urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting certifi>=2017.4.17 (from requests>=2.19.0->pandas_datareader)
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.16.0)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached lxml-4.9.3-cp38-cp38-win_amd64.whl (3.9 MB)
Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Using cached charset_normalizer-3.2.0-cp38-cp38-win_amd64.whl (96 kB)
Using cached urllib3-2.0.4-py3-none-any.whl (123 kB)
Installing collected packages: urllib3, lxml, idna, charset-normalizer, certifi, requests, pandas_datareader
Successfully installed certifi-2023.7.22 charset-normalizer-3.2.0 idna-3.4 lxml-4.9.3 pandas_datareader-0.10.0 requests-2.31.0 urllib3-2.0.4

In [4]:
!pip install yfinance

Collecting yfinance
  Obtaining dependency information for yfinance from https://files.pythonhosted.org/packages/a6/78/62db7f2fb2f13fc4b211676668a5a9d20542a6c774d4f6a9ce0000d71347/yfinance-0.2.27-py2.py3-none-any.whl.metadata
  Downloading yfinance-0.2.27-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from yfinance) (1.24.4)
Requirement already satisfied: requests>=2.31 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Using cached multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: lxml>=4.9.1 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from yfinance) (4.9.3)
Collecting appdirs>=1.4.4 (from yfinance)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from yfinance) (2023.3)
Collecting frozendict>=2.3.4 (from yfinance)
  Using cached frozendict-2.3.8-cp38-cp38-win_amd64.whl (35 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting html5lib>=1.1 (from yfinance)
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.11.1->yfinance)
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Requirement already satisfied: six>=1.9 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Collecting webencodings (from html5lib>=1.1->yfinance)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from requests>=2.31->yfinance) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\chlgu\anaconda3\envs\plotly\lib\site-packages (from requests>=2.31->yfinance) (2023.7.22)
Downloading yfinance-0.2.27-py2.py3-none-any.whl (63 kB)
   ---------------------------------------- 0.0/63.2 kB ? eta -:--:--
   -------------------------------------- - 61.4/63.2 kB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 63.2/63.2 kB 1.1 MB/s eta 0:00:00
Installing collected packages: webencodings, multitasking, appdirs, soupsieve, html5lib, frozendict, beautifulsoup4, yfinance
Successfully installed appdirs-1.4.4 beautifulsoup4-4.12.2 frozendict-2.3.8 html5lib-1.1 multitasking-0.0.11 soupsieve-2.4.1 webencodings-0.5.1 yfinance-0.2.27

In [7]:
from pandas_datareader import data as pdr
import yfinance as yf
import pandas as pd

yf.pdr_override()
pdr.get_data_yahoo("005930.KS")

[*********************100%***********************]  1 of 1 completed

               Open     High      Low    Close     Adj Close    Volume
Date
2000-01-04   6000.0   6110.0   5660.0   6110.0   4514.581055  74195000
2000-01-05   5800.0   6060.0   5520.0   5580.0   4122.972656  74680000
2000-01-06   5750.0   5780.0   5580.0   5620.0   4152.527832  54390000
2000-01-07   5560.0   5670.0   5360.0   5540.0   4093.416992  40305000
2000-01-10   5600.0   5770.0   5580.0   5770.0   4263.360840  46880000
...             ...      ...      ...      ...           ...       ...
2023-08-03  69900.0  70200.0  68500.0  68800.0  68800.000000  20087090
2023-08-04  68800.0  69100.0  68200.0  68300.0  68300.000000  12360193
2023-08-07  67700.0  69200.0  67600.0  68500.0  68500.000000  10968505
2023-08-08  69000.0  69100.0  67400.0  67600.0  67600.000000  14664709
2023-08-09  68000.0  69600.0  67900.0  69200.0  69200.000000  15216124

[5923 rows x 6 columns]